### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by debragail**
updated vulnerabilities by running npm audit fix.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement that improves upon existing functionality

## Checklist:

- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by TalAter** [comment]
Please revert the changes done to `DAVToken.json`. That contract has already been deployed to the blockchain and went through an independent security audit.

**Comment by debragail** [comment]
@TalAter there were no changes made, I deleted an emacs artifact #DAVtoken.json# I believe is the change you see.

**Comment by TalAter** [comment]
@debragail I understand those changes are minor and actually beneficial (e.g., the relative urls in the json), but the audit we underwent was for files with a certain signature (hash) and this changes it. Please revert the changes so that the pull request doesn't include changes to those files.

**Comment by debragail** [comment]
Because of the audit should I avoid other types of changes like updates?

**Comment by TalAter** [comment]
We should avoid changes to files related to `DAVToken` and `DAVCrowdSale` (not present in this repo)

**Comment by TalAter** [comment]
I'm closing this and making making this in a separate commit. Simpler than merging conflicts and reverting changes in 3 files.

**Comment by TalAter** [comment]
Updated in 10822290d7aadeb98abac9adc07b234a555f0fd7

**Pull request closed without merging**
